version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      python: 3.7
      # name: version
    commands:
       - pip install -r requirements.txt
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pushd new_site && make html && popd
      # - command
  post_build:
    commands:
      - aws s3 sync new_site/output s3://xku6
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
