AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TestValueParam:
    Type: String
    Description: The value to be provided to lambda function environment


Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Environment:
        Variables:
          TestValue: !Ref TestValueParam
      Handler: handlers.handle_event
      Runtime: python3.6

